export interface MajorityPrompt { readonly question: string; readonly options: readonly [string, string]; }
export const majorityPrompts: readonly MajorityPrompt[] = [
  { question: 'Give the break-room microwave one power.', options: ['Clean itself', 'Silence fish reheaters'] },
  { question: 'Your shift gets a mascot.', options: ['A judgmental owl', 'An enthusiastic potato'] },
  { question: 'Choose a tiny workplace luxury.', options: ['The perfect chair', 'Endless good snacks'] },
  { question: 'Your alarm must use one sound forever.', options: ['A polite duck', 'Your own voice saying get up'] },
  { question: 'Replace the office doorbell.', options: ['Dramatic entrance music', 'A tiny round of applause'] },
  { question: 'Pick a useless superpower.', options: ['Know exactly when toast is ready', 'Always find matching socks'] },
  { question: 'Your coffee machine becomes sentient.', options: ['It gives sincere compliments', 'It tells terrible jokes'] },
  { question: 'Choose a team uniform accessory.', options: ['An unnecessarily long cape', 'Light-up slippers'] },
  { question: 'Upgrade your commute.', options: ['Never hit a red light', 'Always get a seat'] },
  { question: 'A robot does one chore for you.', options: ['Laundry', 'Washing dishes'] },
  { question: 'Choose a meeting replacement.', options: ['A five-line message', 'A silent interpretive dance'] },
  { question: 'Pick a desk companion.', options: ['A miniature dragon', 'A very wise snail'] },
  { question: 'You win one vending-machine privilege.', options: ['Free drinks', 'First pick of new snacks'] },
  { question: 'Pick a strange weather forecast.', options: ['Warm snow', 'Rain that smells like biscuits'] },
  { question: 'Your lunchbox can do one trick.', options: ['Keep food perfect', 'Refill once a day'] },
  { question: 'Choose a new team greeting.', options: ['A solemn salute', 'Finger guns with sound effects'] },
  { question: 'You get a personal soundtrack.', options: ['Epic movie score', 'Relaxing elevator jazz'] },
  { question: 'Every lift ride includes entertainment.', options: ['A very short mystery', 'A live weather report from a hamster'] },
  { question: 'Pick a room with a view.', options: ['Mountains', 'The sea'] },
  { question: 'Choose your snack texture.', options: ['Crunchy', 'Chewy'] },
  { question: 'One appliance follows you around.', options: ['A helpful kettle', 'A loyal vacuum cleaner'] },
  { question: 'Your chair announces something when you sit.', options: ['Welcome back, legend', 'Loading human'] },
  { question: 'Pick a team victory celebration.', options: ['Pizza', 'An extra-long break'] },
  { question: 'You must wear one hat on Fridays.', options: ['A tiny crown', 'An enormous wizard hat'] },
  { question: 'A new button appears on your desk.', options: ['Instant quiet', 'Instant fresh air'] },
  { question: 'Choose an animal to run reception.', options: ['An organised otter', 'A charming capybara'] },
  { question: 'Your phone gains one oddly specific feature.', options: ['Finds lost pens', 'Detects ripe avocados'] },
  { question: 'Pick a midnight treat.', options: ['Something sweet', 'Something salty'] },
  { question: 'Give the staff room a theme.', options: ['Space station', 'Cosy forest cabin'] },
  { question: 'Your next break contains a surprise.', options: ['A friendly puppy visit', 'A perfect ten-minute nap'] }
];
