import type { IllustrationSubject } from '@nightshift/protocol';
export interface MajorityPrompt { readonly art?:readonly [IllustrationSubject,IllustrationSubject]; readonly question: string; readonly options: readonly [string, string]; }
export const majorityPrompts: readonly MajorityPrompt[] = [
  { art: ["speech","luggage"], question:"Choose your holiday superpower.","options":["Speak every language","Never need to pack"]},
  { art: ["rice","house"], question:"Your pet can text one thing.","options":["Honest reviews of your cooking","Reports from the neighbourhood"]},
  { art: ["sock","music"], question:"Trade one minor inconvenience forever.","options":["Always slightly damp socks","Every song stuck on repeat"]},
  { art: ["book","bread"], question:"You inherit a mysterious shop.","options":["A bookstore with secret rooms","A bakery open only at midnight"]},
  { art: ["blanket","cart"], question:"Pick your ridiculous sporting event.","options":["Competitive blanket folding","Synchronised shopping trolley racing"]},
  { art: ["dinosaur","city"], question:"A time machine has one free trip.","options":["See a dinosaur from a safe distance","Visit a city 200 years from now"]},
  { art: ["book","rice"], question:"Your home gets one impossible room.","options":["A library that finds your next favourite book","A kitchen that recreates any meal"]},
  { art: ["pirate","robot"], question:"Choose a dinner-party guest.","options":["A retired pirate with stories","A robot learning to tell jokes"]},
  { art: ["crown","speech"], question:"Pick a festival tradition.","options":["Everyone wears a homemade crown","Every conversation starts with a compliment"]},
  { art: ["shoe","biscuit"], question:"Your suitcase gets lost. Keep one item.","options":["Your favourite shoes","Your favourite snacks"]},
  { art: ["puzzle","cinema"], question:"Choose the ideal rainy afternoon.","options":["Board games with friends","A film and a blanket"]},
  { art: ["microphone","golf"], question:"You must teach an alien one activity.","options":["Karaoke","Mini golf"]},
  { art: ["portal","cape"], question:"Pick an inconvenient magical ability.","options":["Teleport but arrive in pyjamas","Fly but only at walking speed"]},
  { art: ["photo","tree"], question:"Your plants become chatty.","options":["They give decorating advice","They gossip about the birds"]},
  { art: ["fruit","charger"], question:"Choose a tiny daily victory.","options":["Perfectly ripe fruit","A charger exactly where you need it"]},
  { art: ["download","speech"], question:"Your dreams get one feature.","options":["Save and continue tomorrow","Invite a friend"]},
  { art: ["fish","tree"], question:"Spend a night in a strange hotel.","options":["An aquarium bedroom","A treehouse above the clouds"]},
  { art: ["chilli","cheese"], question:"Every meal must have one extra ingredient.","options":["A little chilli","A little cheese"]},
  { art: ["duck","asian-elephant"], question:"Choose your personal parade.","options":["Three ducks and a trumpet","One elephant with a tiny flag"]},
  { art: ["speech","blanket"], question:"You can rescue one forgotten skill.","options":["Remember every name","Fold a fitted sheet perfectly"]},
  { art: ["water","fish"], question: 'Give the break-room microwave one power.', options: ['Clean itself', 'Silence fish reheaters'] },
  { art: ["owl","potato"], question: 'Your shift gets a mascot.', options: ['A judgmental owl', 'An enthusiastic potato'] },
  { art: ["chair","biscuit"], question: 'Choose a tiny workplace luxury.', options: ['The perfect chair', 'Endless good snacks'] },
  { art: ["duck","speech"], question: 'Your alarm must use one sound forever.', options: ['A polite duck', 'Your own voice saying get up'] },
  { art: ["music","handshake"], question: 'Replace the office doorbell.', options: ['Dramatic entrance music', 'A tiny round of applause'] },
  { art: ["bread","sock"], question: 'Pick a useless superpower.', options: ['Know exactly when toast is ready', 'Always find matching socks'] },
  { art: ["speech","speech"], question: 'Your coffee machine becomes sentient.', options: ['It gives sincere compliments', 'It tells terrible jokes'] },
  { art: ["cape","shoe"], question: 'Choose a team uniform accessory.', options: ['An unnecessarily long cape', 'Light-up slippers'] },
  { art: ["traffic","chair"], question: 'Upgrade your commute.', options: ['Never hit a red light', 'Always get a seat'] },
  { art: ["laundry","dishes"], question: 'A robot does one chore for you.', options: ['Laundry', 'Washing dishes'] },
  { art: ["speech","music"], question: 'Choose a meeting replacement.', options: ['A five-line message', 'A silent interpretive dance'] },
  { art: ["dragon","snail"], question: 'Pick a desk companion.', options: ['A miniature dragon', 'A very wise snail'] },
  { art: ["cup","biscuit"], question: 'You win one vending-machine privilege.', options: ['Free drinks', 'First pick of new snacks'] },
  { art: ["ice","biscuit"], question: 'Pick a strange weather forecast.', options: ['Warm snow', 'Rain that smells like biscuits'] },
  { art: ["rice","rice"], question: 'Your lunchbox can do one trick.', options: ['Keep food perfect', 'Refill once a day'] },
  { art: ["handshake","handshake"], question: 'Choose a new team greeting.', options: ['A solemn salute', 'Finger guns with sound effects'] },
  { art: ["cinema","music"], question: 'You get a personal soundtrack.', options: ['Epic movie score', 'Relaxing elevator jazz'] },
  { art: ["book","speech"], question: 'Every lift ride includes entertainment.', options: ['A very short mystery', 'A live weather report from a hamster'] },
  { art: ["mountain","ocean"], question: 'Pick a room with a view.', options: ['Mountains', 'The sea'] },
  { art: ["biscuit","candy"], question: 'Choose your snack texture.', options: ['Crunchy', 'Chewy'] },
  { art: ["kettle","vacuum"], question: 'One appliance follows you around.', options: ['A helpful kettle', 'A loyal vacuum cleaner'] },
  { art: ["speech","robot"], question: 'Your chair announces something when you sit.', options: ['Welcome back, legend', 'Loading human'] },
  { art: ["pizza","clock"], question: 'Pick a team victory celebration.', options: ['Pizza', 'An extra-long break'] },
  { art: ["crown","hat"], question: 'You must wear one hat on Fridays.', options: ['A tiny crown', 'An enormous wizard hat'] },
  { art: ["ear","atmosphere"], question: 'A new button appears on your desk.', options: ['Instant quiet', 'Instant fresh air'] },
  { art: ["otter","capybara"], question: 'Choose an animal to run reception.', options: ['An organised otter', 'A charming capybara'] },
  { art: ["pen","avocado"], question: 'Your phone gains one oddly specific feature.', options: ['Finds lost pens', 'Detects ripe avocados'] },
  { art: ["doughnut","cheese"], question: 'Pick a midnight treat.', options: ['Something sweet', 'Something salty'] },
  { art: ["spaceship","tree"], question: 'Give the staff room a theme.', options: ['Space station', 'Cosy forest cabin'] },
  { art: ["puppy","sleep"], question: 'Your next break contains a surprise.', options: ['A friendly puppy visit', 'A perfect ten-minute nap'] }
];
