export interface WordCard { readonly word: string; readonly category: string; }
export const wordCards: readonly WordCard[] = [
  {"word":"avalanche","category":"Nature & wildlife"},
  {"word":"aurora","category":"Nature & wildlife"},
  {"word":"firefly","category":"Nature & wildlife"},
  {"word":"jellyfish","category":"Nature & wildlife"},
  {"word":"platypus","category":"Nature & wildlife"},
  {"word":"origami","category":"Music, crafts & play"},
  {"word":"puppet","category":"Music, crafts & play"},
  {"word":"turntable","category":"Music, crafts & play"},
  {"word":"pretzel","category":"Food & treats"},
  {"word":"dumpling","category":"Food & treats"},
  {"word":"saffron","category":"Food & treats"},
  {"word":"pistachio","category":"Food & treats"},
  {"word":"stethoscope","category":"Tools & gadgets"},
  {"word":"periscope","category":"Tools & gadgets"},
  {"word":"catapult","category":"Objects & structures"},
  {"word":"drawbridge","category":"Objects & structures"},
  {"word":"toboggan","category":"Travel & adventure"},
  {"word":"unicycle","category":"Travel & adventure"},
  {"word":"tapestry","category":"Objects & structures"},
  {"word":"terrarium","category":"Objects & structures"},
  {"word":"hammock","category":"Objects & structures"},
  {"word":"compass","category":"Tools & gadgets"},
  {"word":"waffle","category":"Food & treats"},
  {"word":"tornado","category":"Nature & wildlife"},
  {"word":"marshmallow","category":"Food & treats"},
  {"word":"accordion","category":"Music, crafts & play"},
  {"word":"submarine","category":"Travel & adventure"},
  {"word":"chameleon","category":"Nature & wildlife"},
  {"word":"boomerang","category":"Music, crafts & play"},
  {"word":"thermometer","category":"Tools & gadgets"},
  {"word":"igloo","category":"Travel & adventure"},
  {"word":"trampoline","category":"Music, crafts & play"},
  {"word":"magnifier","category":"Tools & gadgets"},
  {"word":"croissant","category":"Food & treats"},
  {"word":"scarecrow","category":"Objects & structures"},
  {"word":"zipper","category":"Objects & structures"},
  {"word":"anchor","category":"Objects & structures"},
  {"word":"lantern","category":"Travel & adventure"},
  {"word":"domino","category":"Music, crafts & play"},
  {"word":"sponge","category":"Tools & gadgets"},
  {"word":"saxophone","category":"Music, crafts & play"},
  {"word":"escalator","category":"Objects & structures"},
  {"word":"seahorse","category":"Nature & wildlife"},
  {"word":"hourglass","category":"Objects & structures"},
  {"word":"windmill","category":"Objects & structures"},
  {"word":"parachute","category":"Travel & adventure"},
  {"word":"pomegranate","category":"Food & treats"},
  {"word":"typewriter","category":"Objects & structures"},
  {"word":"kaleidoscope","category":"Music, crafts & play"},
  {"word":"tongs","category":"Tools & gadgets"}
];
