export interface WordCard { readonly word: string; readonly category: string; }
export const wordCards: readonly WordCard[] = [
  { word: 'hammock', category: 'Something used to relax' },
  { word: 'compass', category: 'Something useful on an adventure' },
  { word: 'waffle', category: 'Something on a breakfast table' },
  { word: 'tornado', category: 'Something powerful in nature' },
  { word: 'marshmallow', category: 'Something sweet' },
  { word: 'accordion', category: 'Something that makes music' },
  { word: 'submarine', category: 'A way to travel' },
  { word: 'chameleon', category: 'An unusual animal' },
  { word: 'boomerang', category: 'Something you throw' },
  { word: 'thermometer', category: 'Something that measures' },
  { word: 'igloo', category: 'A place to take shelter' },
  { word: 'trampoline', category: 'Something for outdoor fun' },
  { word: 'magnifier', category: 'Something that helps you see' },
  { word: 'croissant', category: 'Something from a bakery' },
  { word: 'scarecrow', category: 'Something found on a farm' },
  { word: 'zipper', category: 'Something on clothing' },
  { word: 'anchor', category: 'Something found on a boat' },
  { word: 'lantern', category: 'Something taken camping' },
  { word: 'domino', category: 'Something used in a game' },
  { word: 'sponge', category: 'Something used for cleaning' },
  { word: 'saxophone', category: 'Something on a stage' },
  { word: 'escalator', category: 'Something in a shopping centre' },
  { word: 'seahorse', category: 'Something in the ocean' },
  { word: 'hourglass', category: 'Something that tracks time' },
  { word: 'windmill', category: 'Something with moving parts' },
  { word: 'parachute', category: 'Something used high above the ground' },
  { word: 'pomegranate', category: 'Something in a fruit bowl' },
  { word: 'typewriter', category: 'Something used to communicate' },
  { word: 'kaleidoscope', category: 'Something colourful' },
  { word: 'tongs', category: 'Something used in a kitchen' }
];
